config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'web/welcome#show'

  namespace :api do
    post 'checks', to: 'github_webhooks#checks'
  end

  scope module: :web do
    post 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth
    delete 'auth/logout', to: 'auth#destroy'

    resources :repositories, only: %i[index show new create destroy] do
      scope module: :repositories do
        resources :checks, only: %i[show create]
      end
    end
  end
end

app/views/layouts/shared/_flash.html.slim
div data-turbo-temporary=true
  - flash.each do |type, msg|
    .toast *{ class: %w[position-fixed top-0 mt-5 end-0 me-5 z-1] << flash_class(type), 'data-controller': 'toast' }
      .d-flex
        .toast-body
          = msg
        button.btn-close *{ class: %w[me-2 m-auto], type: 'button', 'data-bs-dismiss': 'toast', 'aria-label': 'Close' }

app/views/layouts/shared/_footer.html.slim
footer.footer.bg-dark-subtle.mt-auto
  .container-xl.text-center
    = t('repository_analyzer', year: DateTime.now.year)

app/views/layouts/shared/_header.html.slim
header.px-3.d-flex *{ class: %w[flex-wrap align-items-center \
  justify-content-center justify-content-md-between \
  py-3 mb-4 border-bottom] }
  = link_to root_path do
    = image_tag 'logo.jpg', height: '30', alt: 'logo'
  .col
    ul.nav.d-flex.justify-content-between
      li = link_to t('home'), root_path, class: 'nav-link'
      - if signed_in?
        .col-md.d-flex.justify-content-between
          li = link_to t('repositories'), repositories_path, class: 'nav-link'
          li
            = link_to '#', class: 'nav-link py-0', data: { 'bs-toggle': 'dropdown' }, aria: { haspopup: true, expanded: false } do
              = avatar_for current_user, height: '40'
            ul.dropdown-menu
              li = link_to t('sign_out'), auth_logout_path, data: { turbo_method: :delete }, class: 'dropdown-item'
      - else
        li
          = form_tag auth_request_path('github'), method: 'post', data: { turbo: false } do
            = button_tag type: 'submit', class: 'nav-link' do
              i.bi.bi-github.me-2
              = t('sign_in')