config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'web/welcome#show'

  namespace :api do
    post 'checks', to: 'github_webhooks#checks'
  end

  scope module: :web do
    post 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth
    delete 'auth/logout', to: 'auth#destroy'

    resources :repositories, only: %i[index show new create destroy] do
      scope module: :repositories do
        resources :checks, only: %i[show create]
      end
    end
  end
end

app/models/repository.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: repositories
#
#  id         :integer          not null, primary key
#  clone_url  :string
#  full_name  :string
#  git_url    :string
#  language   :string
#  name       :string
#  ssh_url    :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  github_id  :integer
#  user_id    :integer          not null
#
# Indexes
#
#  index_repositories_on_user_id  (user_id)
#
# Foreign Keys
#
#  user_id  (user_id => users.id)
#
class Repository < ApplicationRecord
  RELEVANT_FIELDS = %i[full_name git_url language name ssh_url clone_url].freeze
  SUPPORTED_LANGUAGES = %i[javascript ruby].freeze

  include Presentable
  extend Enumerize

  belongs_to :user
  has_many :checks, dependent: :destroy, class_name: 'Repository::Check'

  enumerize :language, in: SUPPORTED_LANGUAGES

  validates :github_id, presence: true

  def directory_path
    Rails.root.join(Dir.tmpdir, 'repositories/', full_name)
  end

  def being_checked?
    checks.last.present? && (checks.last.created? || checks.last.in_process?)
  end
end

app/models/repository/check.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: repository_checks
#
#  id            :integer          not null, primary key
#  aasm_state    :string
#  commit_hash   :string
#  issues        :json
#  issues_count  :integer          default(0)
#  passed        :boolean          default(FALSE)
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  repository_id :integer          not null
#
# Indexes
#
#  index_repository_checks_on_repository_id  (repository_id)
#
# Foreign Keys
#
#  repository_id  (repository_id => repositories.id)
#
class Repository::Check < ApplicationRecord
  include AASM

  belongs_to :repository

  aasm do
    state :created, initial: true
    state :in_process, :failed, :finished

    event :start do
      transitions from: :created, to: :in_process
    end

    event :fail do
      transitions from: :in_process, to: :failed
    end

    event :finish do
      transitions from: :in_process, to: :finished
    end
  end

  include Repository::CheckRepository

  def with_issues?
    issues_count.positive?
  end
end

app/controllers/web/repositories/application_controller.rb
# frozen_string_literal: true

class Web::Repositories::ApplicationController < Web::ApplicationController
  before_action :authenticate_user
end

app/controllers/web/repositories/checks_controller.rb
# frozen_string_literal: true

class Web::Repositories::ChecksController < Web::Repositories::ApplicationController
  def show
    repository = Repository.find params[:repository_id]
    authorize repository, policy_class: Repository::CheckPolicy

    @check = repository.checks.find params[:id]
    @issues = JSON.parse(@check.issues, symbolize_names: true) if @check.issues.present?
  end

  def create
    repository = current_user.repositories.find params[:repository_id]
    authorize repository, policy_class: Repository::CheckPolicy

    check = Repository::Check.create(repository:)
    if check
      CheckRepositoryJob.perform_later(check.id)
      f :success, redirect: repository_path(repository)
    else
      f :error, redirect: repository_path(repository), status: :unprocessable_entity
    end
  end
end

app/controllers/web/repositories_controller.rb
# frozen_string_literal: true

class Web::RepositoriesController < Web::ApplicationController
  before_action :authenticate_user

  def index
    @repositories = current_user.repositories.includes([:checks]).order(full_name: :asc).map(&:decorate)
  end

  def show
    @repository = Repository.find params[:id]
    authorize @repository

    @checks = @repository.checks.order_by_created_at
  end

  def new
    @client_repos = fetch_suitable_client_repos
    @repository = Repository.new
  end

  def create
    @client_repos = fetch_suitable_client_repos
    @repository = current_user.repositories.build(repository_params)

    if @repository.save
      SetupRepositoryJob.perform_later(@repository.id)
      f :success, redirect: repository_path(@repository)
    else
      # NOTE: status :see_other to pass specific Hexlet test
      f :error, now: true, render: :new, status: :see_other
    end
  end

  def destroy
    repository = Repository.find params[:id]
    authorize repository

    if repository.destroy
      f :success, redirect: repositories_path, status: :see_other
    else
      f :error, redirect_back: true, redirect: repositories_path, status: :unprocessable_entity
    end
  end

  private

  def repository_params
    params.require(:repository).permit(:github_id)
  end

  def fetch_suitable_client_repos
    RepositoryService.fetch_repositories!(current_user)
                     .select { |r| r[:language].present? && Repository::SUPPORTED_LANGUAGES.include?(r[:language].downcase.to_sym) }
                     .reject { |r| current_user.repositories.map(&:github_id).include? r[:id] }
  end
end

app/helpers/repositories_helper.rb
# frozen_string_literal: true

module RepositoriesHelper
  def github_commit_url(repository, commit_hash)
    "https://github.com/#{repository.full_name}/commit/#{commit_hash}"
  end

  def github_file_url(repository, commit_hash, file_path)
    "https://github.com/#{repository.full_name}/tree/#{commit_hash}/#{file_path}"
  end
end

app/views/web/repositories/_check_row.html.slim
tr *{ id: dom_id(check.repository, :check_row) }
  td scope='row'
    = link_to check.id, repository_check_path(check.repository, check)
  td = check.aasm.human_state
  td
    - if check.finished? || check.failed?
      = link_to check.commit_hash, github_commit_url(check.repository, check.commit_hash), target: '_blank', rel: :noopener
    - else
      = t('no_info')
  td = check.passed
  td = l(check.created_at, format: :short)

app/views/web/repositories/_repositories_table.html.slim
section#repositories
  table.table.table-hover
    thead
      tr
        th scope='col' = t('.name')
        th scope='col' = t('.language')
        th scope='col' = t('.last_check_status')
    tbody
      - repositories.each do |repository|
        tr
          td = link_to repository.name, repository
          td = repository.language
          td = repository.last_check_status

app/views/web/repositories/_repository.html.slim
section.border-bottom *{ id: dom_id(repository) }
  dl
    .d-flex.gap-3
      dt.mb-3 = han(Repository, :name)
      dd = repository.name
    .d-flex.gap-3
      dt.mb-3 = han(Repository, :language)
      dd = repository.language
    .d-flex.gap-3
      dt.mb-3 = han(Repository, :created_at)
      dd = l(repository.created_at, format: :long)
    .d-flex.gap-3
      dt.mb-3 = han(Repository, :updated_at)
      dd = l(repository.updated_at, format: :long)

section
  table.table.table-striped
    thead
      tr
        th
        th scope='col'
          = han(Repository::Check, :state)
        th scope='col'
          = han(Repository::Check, :commit_hash)
        th scope='col'
          = han(Repository::Check, :passed)
        th scope='col'
          = han(Repository::Check, :created_at)
    tbody *{ id: dom_id(repository, :table) }
      - checks.order_by_created_at.each do |check|
        = render partial: 'check_row', locals: { check: }

app/views/web/repositories/index.html.slim
.row.mb-3
  = link_to new_repository_path do
    i.bi.bi-plus.me-1
    = t('.add_repository')

= render partial: 'repositories_table', locals: { repositories: @repositories }

app/views/web/repositories/new.html.slim
h1 = t('.add_new_repository')

= simple_form_for @repository, url: repositories_path do |f|
  = f.input :github_id, collection: @client_repos.map { |r| [r[:full_name], r[:id]] }
  = f.button :submit, class: 'btn-primary'

app/views/web/repositories/show.html.slim
.d-flex.justify-content-between.align-items-center
  div
    h1 = @repository.full_name
  div
    = link_to repository_path(@repository), class: 'btn btn-danger', data: { turbo_method: :delete, turbo_confirm: t('destroy_confirmation') } do
      i.bi.bi-trash3.me-1
      = t('remove')

menu.px-0
  = link_to repository_checks_path(@repository), class: "btn btn-primary #{class_names(disabled: @repository.decorate.check_disabled?)}", data: { turbo_method: :post } do
    i.bi.bi-rocket-takeoff.me-1
    = t('.check')

= render partial: 'repository', locals: { repository: @repository, checks: @checks }